### paduoda visus gyvūnus.
GET http://localhost:3003/

### įkelia vieną gyvūną.
POST http://localhost:3003/

### by type “/pets/:type”, kuris dinaminis ir paduoda įrašyto tipo gyvūnus (pvz tik šunis).
GET 